fn main() {
    tauri_build::try_build(tauri_build::Attributes::new().app_manifest(
        tauri_build::AppManifest::new().commands(&[
            "get_proxy_port",
            "get_stream_metadata",
            "open_url",
            "set_close_to_tray",
            "set_autostart",
            "is_autostart_enabled",
            "start_recording",
            "stop_recording",
            "is_recording",
            "check_for_updates",
            "install_update",
            "restart_app",
        ]),
    ))
    .unwrap();
}
